export interface KeyValue<K = number, V = string> {
  key: K;
  value: V;
}
export const tevekenysegList = [
  { key: 287, value: 'gyűjtőállomás üzemeltetés to-be'},
  { key: 288, value: 'rakodóhely üzemeltetés'},
  { key: 292, value: 'tenyésztőszervezet működtetése'},
  { key: 293, value: 'minősítő hely üzemeltetése'},
  { key: 294, value: 'minősítő szervezeti tevékenység'},
  { key: 295, value: 'vágóállatok vágás utáni minősítése'},
  { key: 296, value: 'legelő üzemeltetés'},
  { key: 297, value: 'méhanyanevelés'},
  { key: 298, value: 'szúróhely üzemeltetés'},
  { key: 299, value: 'spermagyűjtés és spermatárolás'},
  { key: 300, value: 'mesterséges termékenyítő állomás üzemeltetés to-be'},
  { key: 301, value: 'embrióátültető állomás üzemeltetés'},
  { key: 302, value: 'mobil embrióátültető állomás üzemeltetés'},
  { key: 303, value: 'halászati termékek előállítása to-be'},
  { key: 304, value: 'állatok vágása to-be'},
  { key: 305, value: 'vadhús (lőtt vad) előállítás to-be'},
  { key: 306, value: 'apróvadgazdálkodás to-be'},
  { key: 307, value: 'állatkert üzemeltetés to-be'},
  { key: 308, value: 'állatkísérleti létesítmény üzemeltetés to-be'},
  { key: 309, value: 'állatvásártér, állatpiac, állatkiállítási hely létesítése to-be'},
  { key: 310, value: 'halkeltetés to-be'},
  { key: 311, value: 'vadaskert üzemeltetés'},
  { key: 312, value: 'vadaspark üzemeltetés'},
  { key: 313, value: 'vadfarm üzemeltetés to-be'},
  { key: 314, value: 'víziállat-tenyésztő vállalkozás to-be'},
  { key: 315, value: 'kísérleti haszonállat tenyésztés'},
  { key: 316, value: 'haszonállat tartó menhely üzemeltetés'},
  { key: 320, value: 'kislétszámú állattartás to-be'},
  { key: 321, value: 'nagylétszámú állattartás to-be'},
  { key: 322, value: 'méhtartás to-be'},
  { key: 323, value: 'baromfi keltetés to-be'},
  { key: 324, value: 'kereskedői telep üzemeltetés to-be'},
  { key: 325, value: 'karanténozás (karantén telep üzemeltetés) to-be'},
  { key: 326, value: 'ellenőrző állomás (állatpihentető) üzemeltetés to-be'},
  { key: 342, value: 'DEMO gtir tevékenység'},
] as KeyValue[]